server:
  port: ${SERVER_PORT:8080}
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
  application:
    name: ecommerce-semantic-search

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s

  data:
    elasticsearch:
      repositories:
        enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/ecomhub_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database-platform: org.hibernate.dialect.MySQL5Dialect

  flyway:
    enabled: true
    baseline-on-migrate: true # Cho phép dùng baseline
    locations: classpath:db/migration
    repair-on-fail: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: nkux nvdd ymbt uglj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    root: INFO
    com.ecommerce: ${LOGGING_LEVEL:DEBUG}
    org.springframework.security: INFO

payment:
  exchange-rate:
    vnd-to-usd: 25450.00
  momo:
    partner-code: MOMO
    access-key: F8BBA842ECF85
    secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
    endpoint: "https://test-payment.momo.vn/v2/gateway/api/create"
    callback-url: https://napping-squash-majorette.ngrok-free.dev/api/v1/payments/webhook/momo
    return-url: https://napping-squash-majorette.ngrok-free.dev/payment-success
  vnpay:
    tmn-code: EJBUYER8
    hash-secret: MN9VXSQGKWYIZYSQEHEJ80UJARUF6ZKY
    url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    ipn-url: https://napping-squash-majorette.ngrok-free.dev/api/v1/payments/webhook/vnpay
    return-url: https://napping-squash-majorette.ngrok-free.dev/api/v1/payments/callback/vnpay
  paypal:
    client-id: ${PAYPAL_CLIENT_ID:ATvecIiYFU-JhsFYDSXegNHU84Gvyn53hokG-ckbasgjT9c4wfrmOl9Bdo8YS5ahJC3OsEZrqKPTZc5V}
    client-secret: ${PAYPAL_CLIENT_SECRET:EFcHyHJVqAQBSRpjj_ik9h_yhzNBa74UWgAKvtPpthIXI9FYm0Nqi9uPbyIZ14LZAVsqTy2-hj5lsj7A}
    mode: ${PAYPAL_MODE:sandbox}
    base-url: "https://api-m.sandbox.paypal.com"
    return-url: https://napping-squash-majorette.ngrok-free.dev/api/v1/payments/callback/paypal
    cancel-url: https://napping-squash-majorette.ngrok-free.dev/payment-cancel

cloudinary:
  cloud-name: dxz9mhmjz
  api-key: 187124779552252
  api-secret: ZZDOEKnrO69_53YWCMiBBBk5U3A